#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

echo "🔎 Commit message lint"
FORCE_COLOR=0 npx --no-install commitlint --no-color --edit "$1"

echo "🔎 Type check"
npx tsc --noEmit

echo "🔎 Lint staged files"
npx lint-staged --quiet
